# Generated by Django 6.0.4 on 2026-05-07 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('weekly_goal', models.PositiveIntegerField(help_text='De câte ori pe săptămână?')),
                ('preferred_duration_mins', models.PositiveIntegerField(default=30)),
                ('energy_required', models.CharField(choices=[('Low', 'Low Energy (Relaxing)'), ('Medium', 'Medium Energy (Active)'), ('High', 'High Energy (Demanding)')], default='Medium', max_length=10)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HobbyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('duration_mins', models.PositiveIntegerField()),
                ('completed', models.BooleanField(default=True)),
                ('hobby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='hobbies.hobby')),
            ],
        ),
    ]
