# Generated by Django 6.0.4 on 2026-05-04 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('work', 'Muncă'), ('workout', 'Workout'), ('meeting', 'Întâlnire'), ('shopping', 'Cumpărături'), ('other', 'Altele')], default='other', max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('transport_mode', models.CharField(choices=[('car', 'Mașină'), ('walking', 'Pe jos'), ('transit', 'Transport comun')], default='car', max_length=20)),
                ('estimated_transit_time', models.IntegerField(default=0, help_text='Timpul estimat in minute')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_tasks',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
