# Generated by Django 6.0.4 on 2026-05-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_location',
            field=models.CharField(default='București, România', help_text='Locația de unde își începe ziua utilizatorul', max_length=255),
        ),
    ]
