# Generated by Django 6.0.4 on 2026-05-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_default_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_location',
            field=models.CharField(default='Brașov, România', help_text='Locația de unde își începe ziua utilizatorul', max_length=255),
        ),
    ]
