# Generated by Django 6.0.4 on 2026-05-04 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklySplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Luni', 'Luni'), ('Marti', 'Marti'), ('Miercuri', 'Miercuri'), ('Joi', 'Joi'), ('Vineri', 'Vineri'), ('Sambata', 'Sambata'), ('Duminica', 'Duminica')], max_length=15)),
                ('muscle_group', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_splits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'day_of_week')},
            },
        ),
    ]
