# Generated by Django 6.0.4 on 2026-05-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_weeklysplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklysplit',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='routines', to='workouts.exercise'),
        ),
    ]
